[gcp_key]
type = "service_account"
project_id = "data-driven-attributes"
private_key_id = "957b43d1be08439f1b0a8616a27d7f467fac1fb2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD6K9LH8WMYAA+i
NTKUHeOMUZmFmIvXXWnT9QuC2fyi9mgmYhxvc1hwkaN7oo1AJYK3lpkg3V2fmp1t
... (rest of the key as normal text lines) ...
quQK2XBD6RB+mlhxj1rQ0U02p4yRSYkWki20vMAfAwKBgQD+HA9Iyp+uvPn/j3ZA
-----END PRIVATE KEY-----"""
client_email = "538310479238-compute@developer.gserviceaccount.com"
client_id = "105396807136288688343"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/538310479238-compute%40developer.gserviceaccount.com"
